admin_app:
    resource: "@AdminAppBundle/Resources/config/routing.yml"
    prefix:   /admin

front_app:
    resource: "@FrontAppBundle/Resources/config/routing.yml"
    prefix:   /

urban_user:
    resource: "@UrbanUserBundle/Resources/config/routing.yml"
    prefix:   /

urban_calendar:
    resource: "@UrbanCalendarBundle/Resources/config/routing.yml"
    prefix:   /

urban_timeline:
    resource: "@UrbanTimelineBundle/Resources/config/routing.yml"
    prefix:   /