security:
    encoders:
        Urban\UserBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        in_memory:
            memory: ~
        users_db:
            entity: { class: Urban\UserBundle\Entity\User, property: email }

    access_control:
        - { path: ^/admin, roles: [ROLE_USER, ROLE_ADMIN] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            provider: users_db
            form_login:
                login_path: front_app_login
                check_path: front_app_login_check
                username_parameter: urbangarden_user_form_type_login[_username]
                password_parameter: urbangarden_user_form_type_login[_password]