Urban\UserBundle\Entity\AdminUser:
    type: entity
    repositoryClass: Urban\UserBundle\Repository\AdminUserRepository
    table: admin_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
        password:
            column: password
            type: string
            nullable: false
        lastLogin:
            column: last_login
            type: datetime
            nullable: true
        isActive:
            column: is_active
            type: boolean
        name:
            column: name
            type: string
            nullable: true
        surname:
            column: surname
            type: string
            nullable: true
        email:
            column: email
            type: string
            nullable: false
            unique: true

    lifecycleCallbacks:
        preUpdate: [setUpdatedAt]
        prePersist: [setUpdatedAt]