Urban\UserBundle\Entity\User:
    type: entity
    repositoryClass: Urban\UserBundle\Repository\UserRepository
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        password:
            column: password
            type: string
            nullable: false
        lastLogin:
            column: last_login
            type: datetime
        isActive:
            column: is_active
            type: boolean
        name:
            column: name
            type: string
        surname:
            column: surname
            type: string
        email:
            column: email
            type: string
            nullable: false

    lifecycleCallbacks:
        preUpdate: [setUpdatedAt]
        prePersist: [setUpdatedAt]