Urban\UserBundle\Entity\User:
    properties:
        email:
            - Email:
                message: El email no es válido
            - NotBlank:
                message: El email es obligatorio
        password:
            - Length:
                min: 6
                minMessage: Mínimo 6 carácteres
            - NotBlank:
                message: La contraseña es obligatoria